language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - 5.9.devv@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_2d4f739abdf9_key -iv $encrypted_2d4f739abdf9_iv
  -in thandbag.tar.enc -out thandbag.tar -d
- tar xvf thandbag.tar