server:
  port: 8081

spring:
  profiles: real1
  url:
    base: [Application Domain]

logging:
  level:
    root: warn
    com.demo.restapi: info
  file:
    path: /home/ec2-user/logs/rest-api
    max-history: 7